[전호영] 2장: 함께
muhandojeon/Growing-up-together pull request #15
Opened 2024-09-19 10:36 UTC by HoyeongJeon

2024-09-19 10:50 UTC, hyesungoh requested changes
diff가 두 개 잡혔어요 ~ 1장 파일을 지워주세요~

2024-09-20 02:14 UTC, hyesungoh approved these changes
👍 👍 고생하셨어용

2024-09-20 02:14 UTC, hyesungoh commented on 2장/전호영.md
> +- A를 시켰을 때 B,C가 아닌 A를 하는 사람
👍 👍 👍

2024-09-30 06:37 UTC, bbbang105 approved these changes
너무 잘보았습니다👍🏻👍🏻

2024-09-30 06:37 UTC, bbbang105 commented on 2장/전호영.md
> +- 질문을 "잘" 하는 사람
질문을 잘 하는 것 정말 중요하죠

2024-09-30 06:37 UTC, bbbang105 commented on 2장/전호영.md
> +의견이 서로 스며드는 것
좋네요

2024-09-30 06:37 UTC, bbbang105 commented on 2장/전호영.md
> +- 물리적 거리가 가까워야 함 (모각코?)
모각코 하시죠 다음에

2024-09-30 06:37 UTC, bbbang105 commented on 2장/전호영.md
> +**냉소주의는 전염성이 강하다.**</br>
크게 공감하는 부분입니다.
아무리 잘해도 부정적인 사람이랑은 일하기 힘든 것 같아요.

2024-09-30 09:55 UTC, yeonjookang approved these changes

2024-09-30 09:55 UTC, yeonjookang commented on 2장/전호영.md
> +# 같이 일하고 싶은 동료란 어떤 사람인가?
저도 책을 읽고 같이 일하고 싶은 동료를 찾는 것보다 같이 일하고 싶은 동료가 되어야겠다는 생각이 들었어요 :)

2024-09-30 09:55 UTC, yeonjookang commented on 2장/전호영.md
> +과연 나는 상대방의 입장을 이해하며 말하는 사람일까? 다시 말하고 싶지 않은 사람은 아닐까? </br>
기업 프로젝트에서 함께 한 호영님은 최고의 파트너였습니다! :) 덕분에 소통하는 법에 대해 많이 배웠ㅇ어요~!

2024-09-30 11:12 UTC, HoyeongJeon commented on 2장/전호영.md
> +- 물리적 거리가 가까워야 함 (모각코?)
모각코 렛츠고🚀

2024-09-30 11:12 UTC, HoyeongJeon commented on 2장/전호영.md
> +**냉소주의는 전염성이 강하다.**</br>
정말 공감합니다

2024-09-30 11:13 UTC, HoyeongJeon commented on 2장/전호영.md
> +과연 나는 상대방의 입장을 이해하며 말하는 사람일까? 다시 말하고 싶지 않은 사람은 아닐까? </br>
헉 감동🥹
저도 첫 프로젝트를 같이 하게 되어서 너무 행운이었습니다~!

2024-09-30 11:14 UTC, merged