[최서희] 1장: 자라기
muhandojeon/Growing-up-together pull request #6
Opened 2024-09-11 14:12 UTC by karnelll

2024-09-12 13:55 UTC, hyesungoh approved these changes

2024-09-12 13:55 UTC, hyesungoh commented on 1장/서기
> +책에서 말하는 적당한 난이도의 과제가 좋지만, 어려운 과제를 하면서도 성장할 수 있다는 의견에 동의합니다. 꼭 책의 내용에 완전히 동의하지 않아도 된다고 생각합니다.
하하 정말 잘 정리해주셨군요 👍 👍 👍

2024-09-12 13:55 UTC, hyesungoh commented on 1장/최서희.md
> +특히 첫 번째 개발 프로젝트에서 겪은 팀원 간의 소통 부족 문제는 큰 어려움으로 다가왔다. 소통이 원활하지 않으니 업무 효율이 떨어지고 문제 해결에도 시간이 오래 걸렸다. 이를 계기로 소통의 중요성을 절실히 느꼈고, 이후 프로젝트에서는 디스코드, 카카오톡과 더불어 노션을 활용하여 의견을 체계적으로 공유할 수 있도록 했다. 이 덕분에 팀 내 커뮤니케이션이
왜 소통이 부족하셨었나요??

2024-09-19 11:25 UTC, yeyounging approved these changes

2024-09-19 11:25 UTC, yeyounging commented on 1장/서기
서기 수고하셨어요 👍

2024-09-19 11:25 UTC, yeyounging commented on 1장/최서희.md
> +
회고의 중요성 정말 공감합니다 저희 지난 프로젝트도 회고 해봐요 ㅎㅎ

2024-09-19 12:01 UTC, hyesungoh requested changes
2장은 따로 PR 올려주셔야해요~

2024-09-19 14:17 UTC, hyesungoh requested changes
이것도 .. 따로 PR을 만들어..주십쇼 ..

2024-09-19 23:42 UTC, hyesungoh approved these changes

2024-09-20 08:34 UTC, codrin2 approved these changes

2024-09-26 02:07 UTC, merged

2024-09-30 05:23 UTC, karnelll commented on 1장/서기
> +책에서 말하는 적당한 난이도의 과제가 좋지만, 어려운 과제를 하면서도 성장할 수 있다는 의견에 동의합니다. 꼭 책의 내용에 완전히 동의하지 않아도 된다고 생각합니다.
감사합니다☺️

2024-09-30 05:34 UTC, karnelll commented on 1장/최서희.md
> +특히 첫 번째 개발 프로젝트에서 겪은 팀원 간의 소통 부족 문제는 큰 어려움으로 다가왔다. 소통이 원활하지 않으니 업무 효율이 떨어지고 문제 해결에도 시간이 오래 걸렸다. 이를 계기로 소통의 중요성을 절실히 느꼈고, 이후 프로젝트에서는 디스코드, 카카오톡과 더불어 노션을 활용하여 의견을 체계적으로 공유할 수 있도록 했다. 이 덕분에 팀 내 커뮤니케이션이
저희 팀은 총 15명으로 구성되어, 연동, 백엔드, 프론트, 기획으로 역할을 나누어 프로젝트를 진행했습니다. 하지만 인원이 많다 보니 문제 발생 시 이를 팀 전체와 공유하기보다는 각 분야별로 내부에서만 해결하려고 하여, 전반적으로 소통이 부족했던 것 같습니다..!

2024-09-30 05:35 UTC, karnelll commented on 1장/서기
감사합니다😀

2024-09-30 05:35 UTC, karnelll commented on 1장/최서희.md
> +
좋아요ㅎㅎ👍👍